### ISSUE TITLE
Are you ready to adopt AMD standards?

### ISSUE THREAD

**Issue by peigong** [trix/nano#7]
code:
define('nano', [], function(){
      return function (template, data) {
            return template.replace(/{([\w.]*)}/g, function(str, key) {
                  var keys = key.split("."), v = data[keys.shift()];
                  for (var i = 0, l = keys.length; i < l; i++) v = v[keys[i]];
                  return (typeof v !== "undefined" && v !== null) ? v : "";
            });
      };
});

**Comment by defkode** [comment]
it is just a function, anybody can adapt it to any project (copy&paste). let's keep it simple
